services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./sql/AmeriSave:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      REACT_APP_API_URL: http://localhost:5000

volumes:
  mysql_data:
